update

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -202,39 +202,39 @@ jobs:
             ansible-playbook configure-server.yml -i inventory.txt
       - destroy_environment:
           workflowID: ${CIRCLE_WORKFLOW_ID:0:7}         
-      
   run-migrations:
     docker:
-      - image: python:3.10-alpine3.16
+      # Docker image here that supports NodeJS
+      - image: circleci/node:13.8.0
     steps:
+      # Checkout code from git
       - checkout
-      - restore_cache:
-          key: backend-build
-      - attach_workspace:
-          at: .
       - run:
           name: Install dependencies
           command: |
-            apk add --update --no-cache tar gzip nodejs npm aws-cli curl
-      # - run:
-      #     name: Run migrations
-      #     command: |
-      #       cd backend
-      #       npm install
-      #       npm run build
-      #       npm run migrations > migrations_dump.txt
-      #       ls 
-      #       cat migrations_dump.txt
-
+            apk add --update --no-cache tar gzip aws-cli curl
       - run:
           name: Run migrations
           command: |
+            echo ENVIRONMENT=production > "backend/.env"
+            echo TYPEORM_CONNECTION=postgres >> "backend/.env"
+            echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> "backend/.env"
+            echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> "backend/.env"
+            echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> "backend/.env"
+            echo NODE_ENV=production >> "backend/.env"
+            echo TYPEORM_HOST=$TYPEORM_HOST >> "backend/.env"
+            echo TYPEORM_PORT=$TYPEORM_PORT >> "backend/.env"
+            echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> "backend/.env"
+            echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> "backend/.env"
+            echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> "backend/.env"
             cd backend
-            pwd
-            npm install
-            npm run migrations > migrations_dump.txt
-            ls -la
-            cat ./migrations_dump.txt
+            sudo npm install
+            npm audit fix --audit-level=critical --force
+            npm run build
+            sudo npm run migrations > migration.log
+            cat migration.log
+            migration_succesful=$(cat migration.log | grep -c "has been executed successfully")
+            if [ $migration_succesful > 0 ]; then exit 0; else exit 1; fi;
       - run:
           name: Send migration status to kvdb.io 
           command: |   
@@ -250,15 +250,65 @@ jobs:
                 echo "Database migration has failed, verify DB setup!"
                 curl -k https://kvdb.io/K8deufxEQMDTGfRBmCGog5/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d 'failure'
               fi
-      - persist_to_workspace:
-          root: .
-          paths:
-            - backend/migrations_dump.txt
-      - save_cache:
-          paths: [backend/node-modules]
-          key: backend-build
-      - destroy_environment:
-          workflowID: ${CIRCLE_WORKFLOW_ID:0:7}    
+      # - revert-migrations
+      # - destroy-environment
+
+  # run-migrations:
+  #   docker:
+  #     - image: python:3.10-alpine3.16
+  #   steps:
+  #     - checkout
+  #     - restore_cache:
+  #         key: backend-build
+  #     - attach_workspace:
+  #         at: .
+  #     - run:
+  #         name: Install dependencies
+  #         command: |
+  #           apk add --update --no-cache tar gzip nodejs npm aws-cli curl
+  #     # - run:
+  #     #     name: Run migrations
+  #     #     command: |
+  #     #       cd backend
+  #     #       npm install
+  #     #       npm run build
+  #     #       npm run migrations > migrations_dump.txt
+  #     #       ls 
+  #     #       cat migrations_dump.txt
+
+  #     - run:
+  #         name: Run migrations
+  #         command: |
+  #           cd backend
+  #           pwd
+  #           npm install
+  #           npm run migrations > migrations_dump.txt
+  #           ls -la
+  #           cat ./migrations_dump.txt
+  #     - run:
+  #         name: Send migration status to kvdb.io 
+  #         command: |   
+  #             ls
+  #             if grep -q "has been executed successfully." ./backend/migrations_dump.txt
+  #             then
+  #                 # If you are using memstash.io, generate the token "7933fe63-4687-4fa1-8426-aa25aa1730ec" on the website
+  #                 # curl -H "Content-Type: text/plain" -H "token: 7933fe63-4687-4fa1-8426-aa25aa1730ec" --request PUT --data "1" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
+  #                 # If you are using kvdb.io, generate the bucket ID "9GE4jRtKznmVKRfvdBABBe" in your local terminal first
+  #               echo "Database migration has been executed successfully"
+  #               curl https://kvdb.io/K8deufxEQMDTGfRBmCGog5/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d 'success'
+  #             else
+  #               echo "Database migration has failed, verify DB setup!"
+  #               curl -k https://kvdb.io/K8deufxEQMDTGfRBmCGog5/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d 'failure'
+  #             fi
+  #     - persist_to_workspace:
+  #         root: .
+  #         paths:
+  #           - backend/migrations_dump.txt
+  #     - save_cache:
+  #         paths: [backend/node-modules]
+  #         key: backend-build
+  #     - destroy_environment:
+  #         workflowID: ${CIRCLE_WORKFLOW_ID:0:7}    
 
 #   deploy-frontend:
 #     docker:
@@ -374,11 +424,12 @@ workflows:
       #     filters:
       #       branches:
       #         only: [test]
-      - deploy-infrastructure
-      - configure-infrastructure:
-          requires: [deploy-infrastructure]
-      - run-migrations:
-          requires: [configure-infrastructure]
+      # - deploy-infrastructure
+      # - configure-infrastructure:
+      #     requires: [deploy-infrastructure]
+      # - run-migrations:
+      #     requires: [configure-infrastructure]
+      - run-migrations
       # - deploy-frontend:
       #     requires: [run-migrations]
       # - deploy-backend:
